# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
# Controls when this workflow will run
on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # A workflow run is made up of one or more jobs that an run sequentially or in parallel
env:
  DAY_OF_WEEK: Monday
  testvar: value-1
jobs:
  # Only one single job called build
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Steps represent a sequence of tasks that will be executed as part of the job
    # Checkout code
    - uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo Hello world!

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: main # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build-db:
    needs: build
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"
  package:
    needs: [build, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello macos today is ${{env.DAY_OF_WEEK}}"
  build-api:
    runs-on: macos-latest
    steps:
      - run: echo "Hello API var is ${{ env.testvar }}"
      - name: set-variable
        id: step-1
        run: echo "action_state=yello" >> $GITHUB_ENV
      - name: get-variable
        id: step-2
        run: echo "${{ env.action_state }}" has been set